
@server = https://jidekipro6-urban-couscous-q49xpj4p97w295pj-8030.preview.app.github.dev
@apiserver = {{server}}/api/Artista
###
 GET {{server}}/
###
 GET {{server}}/codigo
###
 GET {{server}}/nombre-codigo

###
GET {{server}}/listar
###
POST {{server}}/api/Artista/nuevo
Content-Type: application/x-www-form-urlencoded

nombre=RAUL&genero=regueton&albun=oasis
###
DELETE {{apiserver}}/eliminar
Content-Type: application/application/x-www-form-urlencoded
id=1