package com.example.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
 
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
 
// imports for use List, Map, String and Object
 
 
import java.lang.String;


@Controller	// This means that this class is a Controller
@RequestMapping(path="/") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private ArtistaRepository repository;
    @GetMapping (path="/")
    public @ResponseBody String home(){
        return "RAUL -QUIJUA BARRERA RAUL";
    }


     @GetMapping (path="/codigo")
    public @ResponseBody String codigo(){ return "A18100778";
    }

     @GetMapping (path="/nombre-codigo")
    public @ResponseBody String nombre(){ return "RAUL - A18100778";
    }


	

	@PostMapping(path="/nuevo") // Map ONLY POST Requests
	public @ResponseBody String nuevo ( @RequestParam String nombre , 
    @RequestParam String genero , @RequestParam String albun ) {
		Artista n = new Artista();
	
		n.setNombre(nombre);
		n.setGenero(genero);
        n.setAlbun(albun);
		repository.save(n);
		return "artista guardado";
	}

	@DeleteMapping(path="/api/Artista/eliminar")
	public @ResponseBody String eliminar (@RequestParam Integer id) {
		Artista n = new Artista();
		n.setId(id);
		repository.delete(n);
		return "curso eliminado";
	}
 


	@GetMapping(path="/api/Artista/listar")
	public @ResponseBody Iterable<Artista> lista() {
		return repository.findAll();
	}
 
 


}
